services:
  - type: web
    name: sales-prediction-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd app && gunicorn --bind 0.0.0.0:$PORT flask_app:app